name: Continuous deployment
on: [push]

jobs:
  #build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: 'latest'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build static files
        run: trunk build --release

      - name: Upload static files as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
